### ISSUE TITLE
Is the code complete ? 

### ISSUE THREAD

**Issue by emanhamed** [mondejar/find_homography#1]

**Comment by mondejar** [comment]
No, sorry

**Comment by emanhamed** [comment]
Can you share with me the complete version if you have it please? or direct me to something similar. 

Thanks

**Comment by mondejar** [comment]
The idea of this repository is quite simple, it just computes the homography, employing the OpenCV method, from a list of manually selected points. What do you want to compute? For homography estimation, I recommend you the OpenCV doc.

**Comment by emanhamed** [comment]
I want to manually decide on the keypoints to be considered for computing the homography. So, I want an interface for that and a function that feeds this to the homography
